# Generated by Django 6.0.1 on 2026-01-07 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=500)),
                ('month', models.CharField(max_length=3)),
                ('year', models.IntegerField()),
                ('api_triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=20)),
                ('file_downloaded', models.BooleanField(default=False)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('skip_reason', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'download_logs',
                'ordering': ['-api_triggered_at'],
                'indexes': [models.Index(fields=['url', 'status'], name='download_lo_url_c44f8b_idx'), models.Index(fields=['month', 'year'], name='download_lo_month_67079f_idx'), models.Index(fields=['api_triggered_at'], name='download_lo_api_tri_645422_idx')],
            },
        ),
    ]
