# Generated by Django 6.0.1 on 2026-01-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amfi_downloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmfiMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=50)),
                ('scheme_category', models.CharField(db_index=True, max_length=200)),
                ('net_inflow', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amfi_monthly_data',
                'ordering': ['month', 'scheme_category'],
                'indexes': [models.Index(fields=['month'], name='amfi_monthl_month_0ca32a_idx'), models.Index(fields=['scheme_category'], name='amfi_monthl_scheme__f84153_idx'), models.Index(fields=['month', 'scheme_category'], name='amfi_monthl_month_c7f6a6_idx')],
                'unique_together': {('month', 'scheme_category')},
            },
        ),
    ]
